package tictim.tfts.contents.fish;

import static tictim.tfts.contents.fish.FishEnv.combine;
import static tictim.tfts.contents.fish.PrimitiveFishEnv.*;

public interface FishEnvs{
	FishEnv ALL_OCEANS = combine(OCEAN_SURFACE, OCEAN_DEEP,
			OCEAN_LUKEWARM_SURFACE, OCEAN_LUKEWARM_DEEP,
			OCEAN_COLD_SURFACE, OCEAN_COLD_DEEP,
			OCEAN_FROZEN_SURFACE, OCEAN_FROZEN_DEEP);

	FishEnv OCEAN = combine(OCEAN_SURFACE, OCEAN_DEEP);
	FishEnv OCEAN_LUKEWARM = combine(OCEAN_LUKEWARM_SURFACE, OCEAN_LUKEWARM_DEEP);
	FishEnv OCEAN_COLD = combine(OCEAN_COLD_SURFACE, OCEAN_COLD_DEEP);
	FishEnv OCEAN_FROZEN = combine(OCEAN_FROZEN_SURFACE, OCEAN_FROZEN_DEEP);

	FishEnv ALL_OCEAN_SURFACES = combine(OCEAN_SURFACE, OCEAN_WARM, OCEAN_LUKEWARM_SURFACE, OCEAN_COLD_SURFACE, OCEAN_FROZEN_SURFACE);
	FishEnv ALL_DEEP_OCEANS = combine(OCEAN_DEEP, OCEAN_LUKEWARM_DEEP, OCEAN_COLD_DEEP, OCEAN_FROZEN_DEEP);

	FishEnv ALL_WATER = combine(ALL_OCEANS, FRESHWATER);
}
